services:
  db:
    image: mysql:8.0
    container_name: adminpanel-phase1a-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: adminpanel
      MYSQL_DATABASE: admin_panel
    ports:
      - "33061:3306"
    volumes:
      - phase1a_mysql_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.phase1a
    container_name: adminpanel-phase1a-web
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html

volumes:
  phase1a_mysql_data:
